SKALE-2319 action workllow development

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -96,54 +96,56 @@ jobs:
         echo ------------ slither version check - after install
         which slither || echo "----> Looks like slither was not installed, next command will fail"
         slither --version || true
+        echo ------------ slither search attempt
+        sudo find / -name slither || true
 
-    - name: INSTALL PREREQUISITES - PROXY - COPY SCRIPTS
-      run: |
-        cd proxy
-        bash ./scripts/copy.sh
-        cd ..
+    # - name: INSTALL PREREQUISITES - PROXY - COPY SCRIPTS
+    #   run: |
+    #     cd proxy
+    #     bash ./scripts/copy.sh
+    #     cd ..
 
-    - name: INSTALL PREREQUISITES - PROXY - PACKAGES
-      run: |
-        cd proxy
-        echo ------------ yarn pass
-        yarn install
-        echo ------------ npx version check
-        which npx || echo "----> Looks like npx was not installed, next command will fail"
-        npx --version
-        echo ------------ buidler version check
-        npx buidler --version
-        cd ..
+    # - name: INSTALL PREREQUISITES - PROXY - PACKAGES
+    #   run: |
+    #     cd proxy
+    #     echo ------------ yarn pass
+    #     yarn install
+    #     echo ------------ npx version check
+    #     which npx || echo "----> Looks like npx was not installed, next command will fail"
+    #     npx --version
+    #     echo ------------ buidler version check
+    #     npx buidler --version
+    #     cd ..
 
-    - name: INSTALL PREREQUISITES - AGENT - PACKAGES
-      run: |
-        cd agent 
-        npm install
-        cd ..
+    # - name: INSTALL PREREQUISITES - AGENT - PACKAGES
+    #   run: |
+    #     cd agent 
+    #     npm install
+    #     cd ..
 
-    - name: INSTALL PREREQUISITES - SKALE-IMA - PACKAGES
-      run: |
-        cd npms/skale-ima
-        npm install
-        cd ../..
+    # - name: INSTALL PREREQUISITES - SKALE-IMA - PACKAGES
+    #   run: |
+    #     cd npms/skale-ima
+    #     npm install
+    #     cd ../..
 
-    - name: START BACKGROUND GANACHE
-      run: |
-        echo ------------ ganache-cli install
-        sudo npm install -g ganache-cli
-        echo ------------ ganache-cli version check
-        which ganache-cli || echo "----> Looks like ganache-cli was not installed, next command will fail"
-        ganache-cli --version
-        echo ------------ ganache-cli startup
-        cd proxy
-        npx ganache-cli --gasLimit 8000000 --quiet --acctKeys ../test/accounts.json &
-        cd ..
+    # - name: START BACKGROUND GANACHE
+    #   run: |
+    #     echo ------------ ganache-cli install
+    #     sudo npm install -g ganache-cli
+    #     echo ------------ ganache-cli version check
+    #     which ganache-cli || echo "----> Looks like ganache-cli was not installed, next command will fail"
+    #     ganache-cli --version
+    #     echo ------------ ganache-cli startup
+    #     cd proxy
+    #     npx ganache-cli --gasLimit 8000000 --quiet --acctKeys ../test/accounts.json &
+    #     cd ..
 
-    - name: PROXY - LINT
-      run: |
-        cd proxy
-        yarn lint #|| travis_terminate 1
-        cd ..
+    # - name: PROXY - LINT
+    #   run: |
+    #     cd proxy
+    #     yarn lint #|| travis_terminate 1
+    #     cd ..
 
     # - name: PROXY - SLITHER
     #   run: |
@@ -157,43 +159,43 @@ jobs:
     #     slither . --filter-path openzeppelin-solidity,@openzeppelin/contracts/ --exclude-informational --exclude reentrancy-events,constant-function,calls-loop,reentrancy-benign,pragma,assembly,blank-lines,timestamp,external-function,constable-states,locked-ether,solc-version,too-many-digits,shadowing-state,shadowing-local,uninitialized-state || travis_terminate 7
     #     cd ..
 
-    - name: PROXY - LINT-2
-      run: |
-        cd proxy
-        yarn tslint #|| travis_terminate 2            
-        cd ..
+    # - name: PROXY - LINT-2
+    #   run: |
+    #     cd proxy
+    #     yarn tslint #|| travis_terminate 2            
+    #     cd ..
 
-    - name: PROXY - GENERATE
-      run: |
-        cd proxy
-        yarn generate
-        bash ./scripts/remove.sh
-        cd ..
+    # - name: PROXY - GENERATE
+    #   run: |
+    #     cd proxy
+    #     yarn generate
+    #     bash ./scripts/remove.sh
+    #     cd ..
 
-    - name: PROXY - TEST
-      run: |
-        cd proxy
-        RUNNING_NETWORK=test bash ./scripts/prepareSkaleManagerComponents.sh
-        yarn test #|| travis_terminate 3
-        cd ..
+    # - name: PROXY - TEST
+    #   run: |
+    #     cd proxy
+    #     RUNNING_NETWORK=test bash ./scripts/prepareSkaleManagerComponents.sh
+    #     yarn test #|| travis_terminate 3
+    #     cd ..
 
-    - name: TEST - PY - PRE-RUN
-      run: |
-        cd test
-        python3 ../scripts/config_from_accounts.py accounts.json config.json
-        pip3 install -r requirements.txt
-        cd ..
+    # - name: TEST - PY - PRE-RUN
+    #   run: |
+    #     cd test
+    #     python3 ../scripts/config_from_accounts.py accounts.json config.json
+    #     pip3 install -r requirements.txt
+    #     cd ..
 
-    - name: TEST - PY - RUN
-      run: |
-        cd test
-        python3 test.py #|| travis_terminate 6
-        cd ..
+    # - name: TEST - PY - RUN
+    #   run: |
+    #     cd test
+    #     python3 test.py #|| travis_terminate 6
+    #     cd ..
 
-    - name: PROXY - COVERAGE
-      run: |
-        cd proxy
-        npx buidler coverage --solcoverjs .solcover.js #|| travis_terminate 4
-        cat coverage/lcov.info | npx codecov
-        cd ..
+    # - name: PROXY - COVERAGE
+    #   run: |
+    #     cd proxy
+    #     npx buidler coverage --solcoverjs .solcover.js #|| travis_terminate 4
+    #     cat coverage/lcov.info | npx codecov
+    #     cd ..
 
