SKALE-2319 action workllow development

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -56,25 +56,42 @@ jobs:
         echo ------------ install
         sudo apt-get install nodejs
         echo ------------ node version check
-        which node || echo "----> Looks like node was not installed"
+        which node || echo "----> Looks like node was not installed, next command will fail"
         node --version
         echo ------------ npm version check
-        which npm || echo "----> Looks like npm was not installed"
+        which npm || echo "----> Looks like npm was not installed, next command will fail"
         npm --version
 
-    # - name: INSTALL PREREQUISITES - PY
-    #   run: |
-    #     echo ------------ py3 installs
-    #     sudo apt-get install python3-pip python3-setuptools python3-dev
-    #     echo ------------ py3 wheel - apt
-    #     sudo apt-get install python3-wheel
-    #     echo ------------ py3 wheel - pip
-    #     pip3 install wheel
-    #     echo ------------ slither analyzer install
-    #     pip3 install slither-analyzer
-    #     echo ------------ slither version check - after install
-    #     which slither || echo "----> Looks like slither was not installed"
-    #     slither --version
+    - name: PY CHECKS
+      run: |
+        echo ------------ python version check
+        which python || echo "----> Looks like python was not installed, next command will fail"
+        python --version
+        echo ------------ python3 version check
+        which python3 || echo "----> Looks like python3 was not installed, next command will fail"
+        python3 --version
+
+    - name: SOLC CHECKS
+      run: |
+        echo ------------ solc install
+        sudo npm install -g solc
+        echo ------------ solc version check
+        which solc || echo "----> Looks like solc was not installed, next command will fail"
+        solc --version
+
+    - name: INSTALL PREREQUISITES - PY
+      run: |
+        echo ------------ py3 installs
+        sudo apt-get install python3-pip python3-setuptools python3-dev
+        echo ------------ py3 wheel - apt
+        sudo apt-get install python3-wheel
+        echo ------------ py3 wheel - pip
+        pip3 install wheel
+        echo ------------ slither analyzer install
+        pip3 install slither-analyzer
+        echo ------------ slither version check - after install
+        which slither || echo "----> Looks like slither was not installed, next command will fail"
+        slither --version || true
 
     - name: INSTALL PREREQUISITES - PROXY - COPY SCRIPTS
       run: |
@@ -88,7 +105,7 @@ jobs:
         echo ------------ yarn pass
         yarn install
         echo ------------ npx version check
-        which npx || echo "----> Looks like npx was not installed"
+        which npx || echo "----> Looks like npx was not installed, next command will fail"
         npx --version
         echo ------------ buidler version check
         npx buidler --version
@@ -111,7 +128,7 @@ jobs:
         echo ------------ ganache-cli install
         sudo npm install -g ganache-cli
         echo ------------ ganache-cli version check
-        which ganache-cli || echo "----> Looks like ganache-cli was not installed"
+        which ganache-cli || echo "----> Looks like ganache-cli was not installed, next command will fail"
         ganache-cli --version
         echo ------------ ganache-cli startup
         cd proxy
@@ -128,7 +145,7 @@ jobs:
     #   run: |
     #     cd proxy
     #     echo ------------ slither version check - before run
-    #     which slither || echo "----> Looks like slither was not installed"
+    #     which slither || echo "----> Looks like slither was not installed, next command will fail"
     #     slither --version
     #     echo ------------ slither steo 1
     #     slither . --filter-path openzeppelin-solidity,@openzeppelin/contracts/ || true            
