Uncomment solc

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -204,17 +204,17 @@ jobs:
         python3 --version
 
     
-    # disabled while solc 0.8 is not compatible with ubuntu 20
-    # - name: SOLC CHECKS
-    #   run: |
-    #     echo ------------ solc install
-    #     # sudo npm install -g solc
-    #     sudo add-apt-repository ppa:ethereum/ethereum
-    #     sudo apt-get update
-    #     sudo apt-get install solc
-    #     echo ------------ solc version check
-    #     which solc || echo "----> Looks like solc was not installed, next command will fail"
-    #     solc --version
+    disabled while solc 0.8 is not compatible with ubuntu 20
+    - name: SOLC CHECKS
+      run: |
+        echo ------------ solc install
+        # sudo npm install -g solc
+        sudo add-apt-repository ppa:ethereum/ethereum
+        sudo apt-get update
+        sudo apt-get install solc
+        echo ------------ solc version check
+        which solc || echo "----> Looks like solc was not installed, next command will fail"
+        solc --version
 
     - name: INSTALL PREREQUISITES - PY
       run: |
