SKALE-4861 github action fix

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -21,34 +21,66 @@ jobs:
     steps:
     - uses: actions/checkout@v2
 
-    - name: Get yarn cache directory path
-      id: yarn-cache-dir-path
-      run: echo "::set-output name=dir::$(yarn cache dir)"
+    # - name: Get yarn cache directory path
+    #   id: yarn-cache-dir-path
+    #   run: echo "::set-output name=dir::$(yarn cache dir)"
 
-    - uses: actions/cache@v2
-      id: yarn-cache
-      with:
-        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
-        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
-        restore-keys: |
-          ${{ runner.os }}-yarn-
+    # - uses: actions/cache@v2
+    #   id: yarn-cache
+    #   with:
+    #     path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
+    #     key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
+    #     restore-keys: |
+    #       ${{ runner.os }}-yarn-
 
-    - uses: actions/cache@v2
+    # - uses: actions/cache@v2
+    #   with:
+    #     path: ~/.cache/pip
+    #     key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
+    #     restore-keys: |
+    #       ${{ runner.os }}-pip-
+
+    - name: Install PYTHON
+      uses: actions/setup-python@v2
       with:
-        path: ~/.cache/pip
-        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
-        restore-keys: |
-          ${{ runner.os }}-pip-
+        python-version: 3.8
 
     - name: Install NODE JS
       uses: actions/setup-node@v2
       with:
         node-version: '16'
 
-    - name: Set up Python
-      uses: actions/setup-python@v2
-      with:
-        python-version: 3.8
+    - name: PREPARE COVERAGE TOOLS
+      run: |
+        echo ------------ install software
+        sudo apt-get install build-essential gcc g++ gcovr lcov || true
+        echo ------------ check gcov
+        gcov --version || true
+        echo ------------ check lcov
+        lcov --version || true
+
+    - name: Install NODE JS
+      run: |
+        echo ------------ uninstall
+        sudo apt-get remove nodejs || true
+        echo ------------ force remove
+        sudo rm -f /usr/local/bin/node || true
+        sudo rm -f /usr/local/bin/npm || true
+        sudo rm -f /usr/bin/node || true
+        sudo rm -f /usr/bin/npm || true
+        echo ------------ download
+        curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
+        echo ------------ install
+        sudo apt-get install nodejs
+        echo ------------ node version check
+        which node || echo "----> Looks like node was not installed, next command will fail"
+        node --version
+        echo ------------ npm version check
+        which npm || echo "----> Looks like npm was not installed, next command will fail"
+        npm --version
+        echo ------------ yarn
+        sudo npm install -g yarn
+        yarn --version
 
     - name: Install project
       working-directory: ${{env.working-directory}}
@@ -178,40 +210,6 @@ jobs:
         # echo ------------ lsusb
         # sudo apt-get install usbutils || true &> /dev/null
         # lsusb -t || echo "No lsusb available" || true
-
-    - name: PREPARE COVERAGE TOOLS
-      run: |
-        echo ------------ install software
-        sudo apt-get install build-essential gcc g++ gcovr lcov || true
-        echo ------------ check gcov
-        gcov --version || true
-        echo ------------ check lcov
-        lcov --version || true
-
-    - name: NODE JS INSTALL
-      run: |
-        echo ------------ uninstall
-        sudo apt-get remove nodejs || true
-        echo ------------ force remove
-        sudo rm -f /usr/local/bin/node || true
-        sudo rm -f /usr/local/bin/npm || true
-        sudo rm -f /usr/bin/node || true
-        sudo rm -f /usr/bin/npm || true
-        echo ------------ download
-        curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
-        echo ------------ install
-        sudo apt-get install nodejs
-        echo ------------ node version check
-        which node || echo "----> Looks like node was not installed, next command will fail"
-        node --version
-        echo ------------ npm version check
-        which npm || echo "----> Looks like npm was not installed, next command will fail"
-        npm --version
-
-    - name: YARN
-      run: |
-          #sudo npm install -g yarn
-          yarn --version
 
     - name: ESLINT
       run: |
