SKALE-2319 action workllow development

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -211,6 +211,5 @@ jobs:
 
     - name: DEPLOY
       run: |
-        echo "DOCKER_USERNAME is:" $DOCKER_USERNAME
-        # echo $DOCKER_PASSWORD
-        bash ./build_image.sh $DOCKER_USERNAME $DOCKER_PASSWORD || true
+        bash ./build_image.sh ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_PASSWORD }} || echo "----> Looks like deploy failed"
+
