Add mainnet ABIs publication

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -12,15 +12,21 @@ on:
     tags:
       - 'custom-release-*'
 
+env:
+  NODE_VERSION: 18
+  PYTHON_VERSION: 3.8
+
 jobs:
   build:
     runs-on: ubuntu-latest
     env:
       DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
       DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
-      PROXY_DIR: "proxy"
+    defaults:
+      run:
+        working-directory: proxy
     steps:
-    - uses: actions/checkout@v2
+    - uses: actions/checkout@v3
 
     - name: Get yarn cache directory path
       id: yarn-cache-dir-path
@@ -44,28 +50,28 @@ jobs:
     - name: Install NODE JS
       uses: actions/setup-node@v2
       with:
-        node-version: '16'
+        node-version: ${{ env.NODE_VERSION }}
 
-    - name: Set up Python 3.8
+    - name: Set up Python
       uses: actions/setup-python@v2
       with:
-        python-version: 3.8
+        python-version: ${{ env.PYTHON_VERSION }}
 
     - name: Build and publish container
       run: |
         export BRANCH=${GITHUB_REF##*/}
         echo "Branch $BRANCH"
-        export VERSION=$(bash ./scripts/calculate_version.sh)
+        export VERSION=$(bash ../scripts/calculate_version.sh)
         echo "VERSION=$VERSION" >> $GITHUB_ENV
         echo "Version $VERSION"
         ( test $BRANCH = "stable" && export PRERELEASE=false ) || export PRERELEASE=true
         echo "PRERELEASE=$PRERELEASE" >> $GITHUB_ENV
         echo ------------ download binaries
-        LIB_BLS_RELEASE_TAG=${{ secrets.LIB_BLS_RELEASE_TAG }} bash ./scripts/download_binaries.sh
+        LIB_BLS_RELEASE_TAG=${{ secrets.LIB_BLS_RELEASE_TAG }} bash ../scripts/download_binaries.sh
         export RELEASE=true
         echo "RELEASE=$RELEASE" >> $GITHUB_ENV
         echo ------------ docker image
-        bash ./scripts/build_image.sh ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_PASSWORD }} #|| echo "----> Looks like deploy failed"
+        bash ../scripts/build_image.sh ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_PASSWORD }} #|| echo "----> Looks like deploy failed"
 
     - name: Prepare for pip package building
       run: |
@@ -73,35 +79,31 @@ jobs:
         python3 -m pip install --user --upgrade twine
 
     - name: Install project
-      working-directory: ${{env.PROXY_DIR}}
-      run: |
-        yarn install
+      run: yarn install
 
     - name: Generate Manifest
-      working-directory: ${{env.PROXY_DIR}}
-      run: |
-        npx hardhat run migrations/generateManifest.ts
+      run: npx hardhat run migrations/generateManifest.ts
 
     - name: Install python testing staff
-      working-directory: ${{env.PROXY_DIR}}
       run: pip3 install -r predeployed/test/requirements.txt
 
     - name: Build predeployed pip package
-      working-directory: ${{env.PROXY_DIR}}
       env:
         VERSION: ${{ env.VERSION }}
-      run: |
-        ./predeployed/scripts/build_package.sh
+      run: ./predeployed/scripts/build_package.sh
 
     - name: Publish predeployed pip package
-      working-directory: ${{env.PROXY_DIR}}
       env:
         PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
-      run: |
-        ./predeployed/scripts/publish_package.sh
+      run: ./predeployed/scripts/publish_package.sh
 
-    - name: Generate ABIs
-      working-directory: ${{env.PROXY_DIR}}/predeployed
+    - name: Generate mainnet ABIs
+      env:
+        VERSION: ${{ env.VERSION }}
+      run: npx hardhat run scripts/generateAbi.ts
+
+    - name: Generate predeployed ABIs
+      working-directory: proxy/predeployed
       env:
         VERSION: ${{ env.VERSION }}
       run: |
@@ -129,7 +131,7 @@ jobs:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
         release_id: ${{ steps.create_release.outputs.id }}
-        assets_path: proxy/predeployed/dist/
+        assets_path: predeployed/dist/
 
     - name: Upload Release Assets
       id: upload-static-data
@@ -138,7 +140,7 @@ jobs:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
         release_id: ${{ steps.create_release.outputs.id }}
-        assets_path: proxy/predeployed/data/
+        assets_path: predeployed/data/
 
     - name: Upload Release Assets
       id: upload-manifest-data
@@ -147,4 +149,12 @@ jobs:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
         release_id: ${{ steps.create_release.outputs.id }}
-        assets_path: proxy/data/ima-schain-*-manifest.json
+        assets_path: data/ima-schain-*-manifest.json
+
+    - name: Upload Release Assets
+      uses: dwenegar/upload-release-assets@v1
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      with:
+        release_id: ${{ steps.create_release.outputs.id }}
+        assets_path: data/*-abi.json
