SKALE-3418 Set production deployment flow

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -1,20 +1,18 @@
 name: Build and publish
-# TODO: return this
-# on:
-#   pull_request:
-#     types: [closed]
-#     branches:
-#       - master
-#       - develop
-#       - beta
-#       - stable
-on: [push, pull_request]
+
+on:
+  pull_request:
+    types: [closed]
+    branches:
+      - master
+      - develop
+      - beta
+      - stable
 
 jobs:
   build:
     runs-on: ubuntu-latest
-    # TODO: return this
-    # if: github.event.pull_request.merged
+    if: github.event.pull_request.merged
     env:
       DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
       DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
@@ -58,14 +56,13 @@ jobs:
         echo "Branch $BRANCH"
         export VERSION=$(bash ./scripts/calculate_version.sh)
         echo "VERSION=$VERSION" >> $GITHUB_ENV
-        echo "Version $VERSION"
-    # TODO: return this
-    #     echo ------------ download binaries
-    #     LIB_BLS_RELEASE_TAG=${{ secrets.LIB_BLS_RELEASE_TAG }} bash ./scripts/download_binaries.sh
-    #     export RELEASE=true
-    #     echo "RELEASE=$RELEASE" >> $GITHUB_ENV
-    #     echo ------------ docker image
-    #     bash ./scripts/build_image.sh ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_PASSWORD }} #|| echo "----> Looks like deploy failed"
+        echo "Version $VERSION"    
+        echo ------------ download binaries
+        LIB_BLS_RELEASE_TAG=${{ secrets.LIB_BLS_RELEASE_TAG }} bash ./scripts/download_binaries.sh
+        export RELEASE=true
+        echo "RELEASE=$RELEASE" >> $GITHUB_ENV
+        echo ------------ docker image
+        bash ./scripts/build_image.sh ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_PASSWORD }} #|| echo "----> Looks like deploy failed"
 
     - name: Prepare for pip package building
       run: |
@@ -83,13 +80,12 @@ jobs:
       run: |        
         ./predeployed/scripts/build_package.sh
 
-    # TODO: return this
-    # - name: Publish predeployed pip package
-    #   working-directory: ${{env.PROXY_DIR}}
-    #   env:
-    #     PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
-    #   run: |        
-    #     ./predeployed/scripts/publish_package.sh
+    - name: Publish predeployed pip package
+      working-directory: ${{env.PROXY_DIR}}
+      env:
+        PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
+      run: |        
+        ./predeployed/scripts/publish_package.sh
 
     - name: Create Release
       id: create_release
