SKALE-1758 Move build_image and calculate_version to scripts/

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -28,9 +28,12 @@ jobs:
         export VERSION=$(bash ./scripts/calculate_version.sh)
         echo "::set-env name=VERSION::$VERSION"
         echo "Version $VERSION"
+        cho ------------ download binaries
+        LIB_BLS_RELEASE_TAG=${{ secrets.LIB_BLS_RELEASE_TAG }} bash ./scripts/download_binaries.sh
         export RELEASE=true
         echo "::set-env name=RELEASE::$RELEASE"
-        bash ./scripts/build_and_publish.sh
+        echo ------------ docker image
+        bash ./scripts/build_image.sh ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_PASSWORD }} #|| echo "----> Looks like deploy failed"
     - name: Checkout code
       uses: actions/checkout@master
     - name: Create Release
