SKALE-3418 Change working dir

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -18,6 +18,7 @@ jobs:
     env:
       DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
       DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
+      PROXY_DIR: "proxy"
     steps:
     - uses: actions/checkout@v2
 
@@ -26,19 +27,20 @@ jobs:
       with:
         python-version: 3.8
 
-    - name: Build and publish container
-      run: |
-        export BRANCH=${GITHUB_REF##*/}
-        echo "Branch $BRANCH"
-        export VERSION=$(bash ./scripts/calculate_version.sh)
-        echo "VERSION=$VERSION" >> $GITHUB_ENV
-        echo "Version $VERSION"
-        echo ------------ download binaries
-        LIB_BLS_RELEASE_TAG=${{ secrets.LIB_BLS_RELEASE_TAG }} bash ./scripts/download_binaries.sh
-        export RELEASE=true
-        echo "RELEASE=$RELEASE" >> $GITHUB_ENV
-        echo ------------ docker image
-        bash ./scripts/build_image.sh ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_PASSWORD }} #|| echo "----> Looks like deploy failed"
+    # TODO: return this
+    # - name: Build and publish container
+    #   run: |
+    #     export BRANCH=${GITHUB_REF##*/}
+    #     echo "Branch $BRANCH"
+    #     export VERSION=$(bash ./scripts/calculate_version.sh)
+    #     echo "VERSION=$VERSION" >> $GITHUB_ENV
+    #     echo "Version $VERSION"
+    #     echo ------------ download binaries
+    #     LIB_BLS_RELEASE_TAG=${{ secrets.LIB_BLS_RELEASE_TAG }} bash ./scripts/download_binaries.sh
+    #     export RELEASE=true
+    #     echo "RELEASE=$RELEASE" >> $GITHUB_ENV
+    #     echo ------------ docker image
+    #     bash ./scripts/build_image.sh ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_PASSWORD }} #|| echo "----> Looks like deploy failed"
 
     - name: Prepare for pip package building
       run: |
@@ -46,12 +48,12 @@ jobs:
         python3 -m pip install --user --upgrade twine
 
     - name: Build predeployed pip package
-      working-directory: ${{env.working-directory}}
+      working-directory: ${{env.PROXY_DIR}}
       run: |        
         ./predeployed/scripts/build_package.sh
 
     - name: Publish predeployed pip package
-      working-directory: ${{env.working-directory}}
+      working-directory: ${{env.PROXY_DIR}}
       run: |        
         ./predeployed/scripts/publish_package.sh
 
